<!-- Codificación del documento -->
<meta charset="UTF-8">

<!-- Autor del proyecto -->
<meta name="author" content="Rebeca Poma">

<!-- Proyecto y aplicación -->
<meta name="application-name" content="RebexTech - Tienda Virtual">

<!-- Herramienta de desarrollo -->
<meta name="generator" content="NetBeans 18">

<!-- Derechos -->
<meta name="copyright" content="RebexTech © 2026">

<!-- Comportamiento para buscadores -->
<meta name="robots" content="index, follow">

<!-- Palabras clave relacionadas con tu proyecto -->
<meta name="keywords" content="RebexTech, tienda online, informática, hardware, MVC, JSP, Java, DAO, productos, categorías">

<!-- Descripción del sitio -->
<meta name="description" content="RebexTech es una tienda virtual desarrollada en Java (MVC, JSP, DAO) especializada en productos de informática y hardware.">

<!-- Adaptación para móviles -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css">



